networks:
  delivery-network:
    name: delivery-network

services:

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    #develop:
      #watch:
        #- action: sync
          #path: ./backend/app
          #target: /app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/backend
    environment:
      - DATABASE_URL=mysql+aiomysql://admin:password@db:3306/delivery
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=delivery
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    networks:
      - delivery-network
    depends_on:
      - db

  db:
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=delivery
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - delivery-network

volumes:
  mysql_data:
