"""initial revision

Revision ID: 5e30c9f3ae09
Revises: 
Create Date: 2025-05-27 22:20:28.663138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e30c9f3ae09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_type',
    sa.Column('id', sa.String(length=36), server_default=sa.text('UUID()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_type_id'), 'package_type', ['id'], unique=False)
    op.create_table('package',
    sa.Column('id', sa.String(length=36), server_default=sa.text('UUID()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('type_id', sa.String(length=36), nullable=False),
    sa.Column('content_cost', sa.Float(), nullable=True),
    sa.Column('delivery_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['package_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_id'), 'package', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_id'), table_name='package')
    op.drop_table('package')
    op.drop_index(op.f('ix_package_type_id'), table_name='package_type')
    op.drop_table('package_type')
    # ### end Alembic commands ###
